version: '3.7'
services:
  main:
    build: .
    command: npm run server
    ports:
      - '8080:8080'
  hapi:
    image: 'hapiproject/hapi:latest'
    ports:
      - '8081:8080'
    configs:
      - source: hapi
        target: /data/hapi/application.yaml
    volumes:
      - hapi-data:/data/hapi
configs:
  hapi:
    external: true
volumes:
  hapi-data:
    external: true
