version: '3.7'
services:
  main:
    build: .
    command: npm run server
    environment:
      FHIR_API: 'http://hapi.fhir.org/baseR4'
    ports:
      - '8080:8080'
configs:
  hapi:
    external: true
