version: '3.7'
services:
  hapi:
    image: 'hapiproject/hapi:latest'
    ports:
      - '8081:8080'
    volumes:
      - ./hapi-data:/usr/local/tomcat/target
  main:
    build: .
    links:
      - hapi
    command: npm run server
    environment:
      FHIR_API: 'http://hapi:8080/fhir'
    ports:
      - '8080:8080'
configs:
  hapi:
    external: true
